DeMaCS-UNICAL/LoIDE

resources/config/properties

Set default port to 8084, as specified in README.md

Set default port to 8084

---

resources/index.html
resources/js/script.js

Added DLV2 support

---

resources/css/style.css
resources/index.html
resources/js/script.js

Fixes #
- Add in local storage the output panel position
- Add "reset" button for solver and editor options

Output panel options

---

resources/js/script.js

Fixes #
Changes proposed in this pull request: 
- Added new command inside ACE editor: Ctrl+Enter/Command-enter "Run" the program

Add new command

---

package.json
resources/index.html
resources/js/script.js

- Now it’s possible to change the name of tabs.

Change tab name   1.7.0

---

package.json
resources/js/script.js

Fixed run option bug fix
- _Disabled temporary_ the restore of run options from local storage

Run options bug fix   1.10.1

---

package.json
resources/index.html
resources/js/script.js

Fixed definitely the run options bug
Fixed the URL decoder
- re-enabled saving run options in the local storage

Bugs fix   1.10.2

---

app.js
package.json
resources/css/style.css
resources/index.html
resources/js/script.js

- Fixed bug that the shortcut to download the project didn't work
- Fixed some bugs and UI improvements
- New solver options section UI
- Improved the editor options UI
- Changed some icons on buttons
- Now the tabs names will be saved with the project when it will be downloaded
- Focus on editor of a tab when it selected from tab navbar
- Improved the share link method
- Added canonical link

New solver options   1.11.0

---

README.md
app.js
config/app-config.json
config/properties
config/services.json
package.json

This pull request is part of a series of requests for `dynamicOptions` branch alignment.
* `properties` file is replaced with a `app-config.json;`
* Added `services.json` file with all the supported services (languages, solvers and executors).
These JSON files are for the future JSON schema implementation.

Dynamic options alignment part 1: Support for different solver executors

---

app.js
package.json

- Wrong parameter name passed to the executor.

Dynamic options alignment

---

resources/js/script.js

- Syntax highlighting only for ASP

dynamic highlighting

---

app.js
config/services.json
package.json
resources/index.pug
resources/js/script.js

* Now the user can choose the executor to use for the program
* DLV2 is placed as the first solver in `services.json` file to became the default choice in the UI

Dynamic options alignment3

---

package.json

Version update after this [commit](https://github.com/DeMaCS-UNICAL/LoIDE/commit/bfa420f81a49a8c8612c5db9a898e7235088f06c).

Version update after bug fix

---

package.json
resources/css/style.css
resources/index.pug
resources/js/script.js

- Changed buttons names and icons on the navbar
- Added a share button on navbar: now it generates an URL that contains all the projects with all the logic programs on the tabs with their name, the language and the solver used and all the solver options added from the user
- Now it's possible to open multiple files. LoIDE will open the contents on more tabs
- Added tooltips on the toolbar buttons
- General improvements
- Fix some UI style elements
- The only output download functionality from the save popover. It will be reimplemented in the next releases.
- Share button from the toolbar. The URL generator now it's moved on the share button on the navbar and the download of the current logic program will be reimplemented in the next releases.

Navbar buttons and open multiple files - 2.3

---

package.json
resources/css/style.css
resources/index.pug
resources/js/script.js

- Tollbar:
1. Changed icons on undo and redo button on the toolbar
2. Added Search/Replace button
3. Added Copy button
4. Added Cut button
5. Added Paste button: supported only on browser that supports the Clipboard API es. Chrome
6. Added back the Download this tab button, that download on txt file the content of the current tab opened 
- Improved Toast/Notification

Toolbar 2.4

---

package.json
resources/js/script.js

- Fixed bug that the first tab can't be checked on "Choose tab to execute" when the last tab was deleted

Release 2.7.1

---

.babelrc
README.md
app.js
config/app-config-schema.json
config/app-config.json
gulpfile.js
package.json
resources/css/style.css
resources/index.pug
resources/js/script.js

- Added new modal that shows the shortcuts
- Added icons on modal titles
- Added some title attribute to buttons
- Added clear output button that clear all the output content
- Added clear tab content on the tab context menu
- Added delete all tabs button
- Added Security Headers
- Added SEO meta tags
- Added Babel Gulp plugin
- Added LoIDE URL param on app-config.json
- Refactored About modal content
- Now the LoIDE shortcuts working when using the editor
- Changed some tooltip names
- Updated Ace editor
- Updated the shortcuts and added new ones
- Updated plugins
- Replaced Keymaster.js with MouseTrap
- Fixed issue with Run automatically option not being enabled by default
- Fixed output panel position bug on mobile devices
- Removed shorthand gulp …

Release 2.9.0

---

README.md
app.js
config/services-schema.json
config/services.json
resources/js/ace/mode/mode-datalog.js
resources/js/script.js

- Support to Datalog language and I-DLV solver
- Now wss is the default protocol to communicate with the executor

Add support to Datalog/I-DLV and to SSL connections

---

README.md
package.json

Added my name in package.json and readme

Added contributor name

---

app.js
config/app-config-schema.json
config/services-schema.json
package.json

- Updated Ajv to 8.0.5
- Updated Pug to 3.0.1

Release 2.11.0
